/* This file was generated by SableCC (http://www.sablecc.org/). */

package Calculator.node;

import Calculator.analysis.*;

@SuppressWarnings("nls")
public final class TAffect extends Token
{
    public TAffect()
    {
        super.setText("\\affect");
    }

    public TAffect(int line, int pos)
    {
        super.setText("\\affect");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAffect(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAffect(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAffect text.");
    }
}
