/* This file was generated by SableCC (http://www.sablecc.org/). */

package Calculator.node;

import Calculator.analysis.*;

@SuppressWarnings("nls")
public final class TCbrt extends Token
{
    public TCbrt()
    {
        super.setText("\\cbrt");
    }

    public TCbrt(int line, int pos)
    {
        super.setText("\\cbrt");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCbrt(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCbrt(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCbrt text.");
    }
}
