/* This file was generated by SableCC (http://www.sablecc.org/). */

package Calculator.node;

import Calculator.analysis.*;

@SuppressWarnings("nls")
public final class TCosh extends Token
{
    public TCosh()
    {
        super.setText("\\cosh");
    }

    public TCosh(int line, int pos)
    {
        super.setText("\\cosh");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCosh(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCosh(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCosh text.");
    }
}
