/* This file was generated by SableCC (http://www.sablecc.org/). */

package Calculator.node;

import Calculator.analysis.*;

@SuppressWarnings("nls")
public final class TFact extends Token
{
    public TFact()
    {
        super.setText("\\fact");
    }

    public TFact(int line, int pos)
    {
        super.setText("\\fact");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFact(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFact(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFact text.");
    }
}
