/* This file was generated by SableCC (http://www.sablecc.org/). */

package Calculator.node;

import Calculator.analysis.*;

@SuppressWarnings("nls")
public final class TTanh extends Token
{
    public TTanh()
    {
        super.setText("\\tanh");
    }

    public TTanh(int line, int pos)
    {
        super.setText("\\tanh");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTanh(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTanh(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTanh text.");
    }
}
